name: CICD

on:
  push:
    branches:
      - develop

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run : |
          git config --global user.name "rheech22"
          git config --global user.email "rheech22@gmail.com"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run deploy